### ISSUE TITLE
Error buying split ticket: found different number of running wallets (0) than expected

### ISSUE THREAD

**Issue by dabuchera** [matheusd/dcr-split-ticket-matcher#70]
Unfortunatly i always get the following error message. Decretion is running, started before the splittickerbuyer. Also tried to change to matcher.decredvoting.com:8475

any suggestion?

Thanks.

**Comment by matheusd** [comment]
Is the wallet open in decrediton?

Also check if you have a `Testnet = 1` in your splitticketbuyer.conf file.

**Comment by dabuchera** [comment]
Yes, the wallet is open and `Testnet = 0`. In my option correct since we use the mainnet

**Comment by matheusd** [comment]
Check if `walletCertFile` is pointing to certificate file for the correct (open) wallet.

Finally the last test you can try is modifying the `dcrwallet.conf` file of the wallet, set `grpclisten = 127.0.0.1:9121` and then set in the splitticketbuyer.conf `wallethost = 127.0.0.1:9121`.

**Comment by dabuchera** [comment]
Perfect. The change of the port was working. Thanks!

**Comment by matheusd** [comment]
:+1:
